spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yumu-db.cae195iepgm5.ap-northeast-2.rds.amazonaws.com:3306/?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: admin
    password: ${DB_PASSWORD}